{% set name = "sphinx-tabs" %}
{% set version = "3.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ba9d0c1e3e37aaadd4b5678449eb08176770e0fc227e769b6ce747df3ceea531

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - sphinx >=2
    - pygments
    - docutils >=0.18.0

test:
  imports:
    - sphinx_tabs

about:
  home: https://github.com/executablebooks/sphinx-tabs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tabbed views for Sphinx
  doc_url: https://sphinx-tabs.readthedocs.io/

extra:
  recipe-maintainers:
    - chrisjsewell
