{% set name = "sphinx-tabs" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7d35a869757bf34375010b77df0f27e836a99e8c595729c322499dc8f965806a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pygments
    - python >=3.6
    - sphinx >=2,<4

test:
  imports:
    - sphinx_tabs

about:
  home: https://github.com/executablebooks/sphinx-tabs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tabbed views for Sphinx
  doc_url: https://sphinx-tabs.readthedocs.io/

extra:
  recipe-maintainers:
    - chrisjsewell
